#! /bin/sh

# Autostart 
pgreg -x sxhkd > /dev/null || sxhkd &
[ -f ~/.Xresources ] && xrdb ~/.Xresources
nitrogen --restore &


# Setup
bspc monitor -d I II III IV V VI VII VIII IX X


# Appearance
bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true



